/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrNavigation: typeof import('@gouvminint/vue-dsfr')['DsfrNavigation']
    DsfrNavigationItem: typeof import('@gouvminint/vue-dsfr')['DsfrNavigationItem']
    DsfrNavigationMenuLink: typeof import('@gouvminint/vue-dsfr')['DsfrNavigationMenuLink']
    DsfrRadioButtonSet: typeof import('@gouvminint/vue-dsfr')['DsfrRadioButtonSet']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidatedDsfrCheckbox: typeof import('./components/ValidatedDsfrCheckbox.vue')['default']
    ValidatedDsfrInput: typeof import('./components/ValidatedDsfrInput.vue')['default']
    ValidatedDsfrRadioButtonSet: typeof import('./components/ValidatedDsfrRadioButtonSet.vue')['default']
    ValidatedDsfrSelect: typeof import('./components/ValidatedDsfrSelect.vue')['default']
  }
}
